# Generated by Django 5.2.17 on 2026-10-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_add_station_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('active', 'Active'), ('inactive', 'Inactive')], max_length=20, null=True),
        ),
    ]
