# Generated by Django 5.2.17 on 2026-10-07 18:10

from django.db import migrations

def forwards(apps, schema_editor):
    Sensor = apps.get_model("monitoring", "Sensor")
    database = schema_editor.connection.alias

    Sensor.objects.using(database).filter(
        active=True,
    ).update(status="active")

    Sensor.objects.using(database).filter(
        active=False,
    ).update(status="inactive")


def backwards(apps, schema_editor):
    Sensor = apps.get_model("monitoring", "Sensor")
    database = schema_editor.connection.alias

    Sensor.objects.using(database).update(status=None)

class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_add_sensor_status_nullable'),
    ]

    operations = [
        migrations.RunPython(
            forwards,
            backwards,
        ),
    ]
