# Generated by Django 5.2.17 on 2026-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_populate_sensor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('active', 'Active'), ('inactive', 'Inactive')], default='unknown', max_length=20),
        ),
    ]
