# Generated by Django 5.2.17 on 2026-10-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_make_sensor_status_required'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE VIEW active_station_codes AS
                SELECT id, code
                FROM monitoring_station
                WHERE active = TRUE
            """,
            reverse_sql="""
                DROP VIEW active_station_codes
            """,
            state_operations=[
                migrations.CreateModel(
                    name="ActiveStationCode",
                    fields=[
                        (
                            "id",
                            models.BigIntegerField(
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "code",
                            models.CharField(max_length=30),
                        ),
                    ],
                    options={
                        "managed": False,
                        "db_table": "active_station_codes",
                    },
                ),
            ],
        ),
    ]
