# Generated by Django 5.2.17 on 2026-10-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_active_station_codes_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
