# Generated by Django 5.2.17 on 2026-10-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_active_station_codes_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='calibration_offset',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6), # type: ignore
        ),
    ]
