# Generated by Django 5.2.17 on 2026-10-08 09:08
from decimal import Decimal

from django.db import migrations

from monitoring.models import Sensor, Station


def forwards(apps, schema_editor):
    Station.objects.filter(
        code__icontains="ALPINE",
    ).update(
        region="alpine",
    )

    Station.objects.exclude(
        code__icontains="ALPINE",
    ).update(
        region="standard",
    )

    Sensor.objects.filter(
        station__region="alpine",
    ).update(
        calibration_offset=Decimal("0.150"),
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "monitoring",
            "0007_station_region",
        ),
    ]

    operations = [
        migrations.RunPython(
            forwards,
        ),
    ]
