# Generated by Django 5.2.17 on 2026-10-08 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "monitoring",
            "0008_initialize_regional_calibration",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE VIEW active_calibrated_sensors AS
                SELECT
                    s.id,
                    s.name,
                    s.calibration_offset,
                    st.code AS station_code
                FROM monitoring_sensor s
                JOIN monitoring_station st
                    ON st.id = s.station_id
                WHERE s.active = TRUE
            """,
            reverse_sql="""
                DROP VIEW active_calibrated_sensors
            """,
        ),
    ]
